apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-consumer
  labels:
    name: demo-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: zexinpeng97/demo-consumer:latest
          env:
          - name: KAFKA_IP
            value: "kafka-service"
          ports:
          - containerPort: 8083
