apiVersion: v1
kind: Pod
metadata:
   name: zookeeper
   lables:
     name: zookeeper
spec:
   containers:
   - name: zookeeper
     image: zookeeper
     ports:
     - containerPort: 2181
     - containerPort: 2888
     - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
    name: port-2181
  - port: 2888
    targetPort: 2888
    name: port-2888
  - port: 3888
    targetPort: 3888
    name: port-3888


