FROM openjdk:11
COPY target/flink-consumer-0.0.1-SNAPSHOT-jar-with-dependencies.jar flink-consumer-0.0.1-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "/flink-consumer-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
